add refresh method
canonical/prometheus-k8s-operator pull request #208
Opened 2022-01-24 20:05 UTC by sed-i

This PR adds a public method for refreshing relations.
This is needed for cos-config to be able to refresh alerts when alerts show up on disk after the last hook fired.

cf. https://github.com/canonical/loki-k8s-operator/pull/76, https://github.com/canonical/grafana-k8s-operator/pull/53

2022-01-24 22:57 UTC, dstathis submitted a review, later dismissed

2022-01-25 07:59 UTC, mmanciop submitted a review, later dismissed
The code change LGTM, but I think this warrants a unit test or two :-)

2022-01-25 20:07 UTC, rbarry82 requested changes
Rename and make the method private?

2022-01-25 20:25 UTC, rbarry82 submitted a review, later dismissed

2022-01-25 20:47 UTC, mmanciop approved these changes
The PR description is outdated, the rest LGTM.

2022-01-25 22:17 UTC, dstathis approved these changes

2022-01-25 22:19 UTC, rbarry82 approved these changes

2022-01-26 14:06 UTC, merged