feat: remote_write_receiver option
canonical/prometheus-k8s-operator pull request #519
Opened 2023-09-06 09:47 UTC by Guillaumebeuzeboc

## Issue
the juju cos setup cannot receive data from the grafana-agent if the grafana -agent is not running inside juju.

## Solution
Add a charm option to enable the remote `remote_write_receiver` feature even when no relation is established.

## Context
IoT devices cannot run juju due to resources constraint, so they must run grafana-agent snap standalone.
This way the COS stack can be used on servers and snaps can be used on devices to export data.

## Notes

This is a draft PR as a suggestion as I am exploring the usage of COS for robots

2023-09-21 11:48 UTC, dstathis commented
This seems like a good idea. What do you think @simskij?

2023-09-21 11:53 UTC, simskij approved these changes

2023-09-21 18:58 UTC, sed-i requested changes
Thanks @Guillaumebeuzeboc!
Ideally we'd want to keep config options minimal or scalable.
Since juju config options cannot be nested, we try to stick to minimal.

2023-09-21 18:58 UTC, sed-i commented on config.yaml
> +  remote_write_receiver:
I think we shouldn't have this config option. Instead, always enable remote write:
Currently, when we enable remote-write, it's enabled for everyone; afaict, there isn't greater risk in enabling it to begin with.

2023-09-22 08:49 UTC, simskij approved these changes

2023-09-22 08:49 UTC, simskij commented on src/charm.py
>              args.append("--web.enable-remote-write-receiver")
```suggestion
        args.append("--web.enable-remote-write-receiver")
```

2023-09-22 08:49 UTC, simskij commented on config.yaml
> +    default: false
```suggestion
```

2023-09-22 08:51 UTC, simskij commented
@Guillaumebeuzeboc would you mind squashing your commits into a signed commit to allow for merging? Thanks.

2023-09-25 12:19 UTC, Guillaumebeuzeboc commented
> @Guillaumebeuzeboc would you mind squashing your commits into a signed commit to allow for merging? Thanks.

Done, let me know if it's all good.
Thanks!

2023-09-26 14:34 UTC, merged